#use_frameworks!

platform :ios, '8.0'

target 'PQNetworking_Example' do
  pod 'PQNetworking', :path => '../'
  pod "CTMediator"

  target 'PQNetworking_Tests' do
    inherit! :search_paths

    
  end
end
